In [434]:
# Import modules
import pandas as pd
import numpy as np
import glob
import os
import sqlite3

# Pipeline Data Cuaca

In [435]:
# Baca semua data cuaca dalam folder
cuaca_files = glob.glob('/content/cuaca/*.csv')

list_cuaca = []

for file in cuaca_files:

    df = pd.read_csv(file, skiprows=3)

    # Ambil nama wilayah dari nama file
    wilayah = os.path.splitext(os.path.basename(file))[0]

    df['Wilayah'] = wilayah

    list_cuaca.append(df)

# Gabungkan seluruh file
df_cuaca_raw = pd.concat(list_cuaca, ignore_index=True)

df_cuaca_raw.head()

,time,temperature_2m_mean (°C),precipitation_sum (mm),relative_humidity_2m_mean (%),Wilayah
0,2018-01-01,26.6,5.6,79,Kabupaten Madiun
1,2018-01-02,26.2,2.8,84,Kabupaten Madiun
2,2018-01-03,26.1,3.1,85,Kabupaten Madiun
3,2018-01-04,25.7,37.4,88,Kabupaten Madiun
4,2018-01-05,26.1,2.8,84,Kabupaten Madiun

Analisis Data Cuaca

In [436]:
df_cuaca_raw['time'].head()

0    2018-01-01
1    2018-01-02
2    2018-01-03
3    2018-01-04
4    2018-01-05
Name: time, dtype: object

In [437]:
df_cuaca_raw['time'].unique()[:5]

array(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
       '2018-01-05'], dtype=object)

In [438]:
df_cuaca_raw['Wilayah'].unique()

array(['Kabupaten Madiun', 'Kabupaten Ponorogo', 'Kabupaten Blitar',
       'Kota Mojokerto', 'Kota Malang', 'Kota Probolinggo',
       'Kabupaten Trenggalek', 'Kabupaten Kediri', 'Kabupaten Mojokerto',
       'Kabupaten Pasuruan', 'Kabupaten Tulungagung',
       'Kabupaten Lumajang', 'Kabupaten Pamekasan', 'Kabupaten Pacitan',
       'Kabupaten Ngawi', 'Kabupaten Sidoarjo', 'Kabupaten Jember',
       'Kabupaten Bangkalan', 'Kabupaten Bojonegoro',
       'Kabupaten Bondowoso', 'Kabupaten Sampang', 'Kota Kediri',
       'Kabupaten Tuban', 'Kabupaten Magetan', 'Kota Pasuruan',
       'Kota Blitar', 'Kabupaten Probolinggo', 'Kabupaten Nganjuk',
       'Kota Madiun', 'Kabupaten Malang', 'Kabupaten Sumenep',
       'Kota Surabaya', 'Kabupaten Banyuwangi', 'Kabupaten Lamongan',
       'Kabupaten Situbondo', 'Kabupaten Jombang', 'Kota Batu',
       'Kabupaten Gresik'], dtype=object)

In [439]:
df_cuaca_raw[
    df_cuaca_raw['Wilayah'] == 'Kabupaten Madiun'
].head()

,time,temperature_2m_mean (°C),precipitation_sum (mm),relative_humidity_2m_mean (%),Wilayah
0,2018-01-01,26.6,5.6,79,Kabupaten Madiun
1,2018-01-02,26.2,2.8,84,Kabupaten Madiun
2,2018-01-03,26.1,3.1,85,Kabupaten Madiun
3,2018-01-04,25.7,37.4,88,Kabupaten Madiun
4,2018-01-05,26.1,2.8,84,Kabupaten Madiun

Analisis

In [440]:
df_cuaca_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97166 entries, 0 to 97165
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   time                           97166 non-null  object
 1   temperature_2m_mean (°C)       97166 non-null  float64
 2   precipitation_sum (mm)         97166 non-null  float64
 3   relative_humidity_2m_mean (%)  97166 non-null  int64
 4   Wilayah                        97166 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 3.7+ MB

In [441]:
df_cuaca_raw.isnull().sum()

time                             0
temperature_2m_mean (°C)         0
precipitation_sum (mm)           0
relative_humidity_2m_mean (%)    0
Wilayah                          0
dtype: int64

In [442]:
df_cuaca_raw.describe()

,temperature_2m_mean (°C),precipitation_sum (mm),relative_humidity_2m_mean (%)
count,97166.000000,97166.000000,97166.000000
mean,26.298230,5.928789,78.839574
std,1.866275,9.752262,10.343713
min,16.000000,0.000000,32.000000
25%,25.300000,0.100000,72.000000
50%,26.400000,1.700000,82.000000
75%,27.500000,8.200000,87.000000
max,32.200000,308.800000,99.000000

Cleaning

In [443]:
# mengubah kolom time dari tipe data object/string menjadi format datetime
df_cuaca_raw['time'] = pd.to_datetime(df_cuaca_raw['time'])

In [444]:
# Mengambil tahun dari kolom time kemudian disimpan kedalam kolom baru bernama tahun
df_cuaca_raw['Tahun'] = df_cuaca_raw['time'].dt.year

# Mengambil bulan dari kolom time kemudian disimpan kedalam kolom baru bernama bulan
df_cuaca_raw['Bulan'] = df_cuaca_raw['time'].dt.month
df_cuaca_raw.head()

,time,temperature_2m_mean (°C),precipitation_sum (mm),relative_humidity_2m_mean (%),Wilayah,Tahun,Bulan
0,2018-01-01,26.6,5.6,79,Kabupaten Madiun,2018,1
1,2018-01-02,26.2,2.8,84,Kabupaten Madiun,2018,1
2,2018-01-03,26.1,3.1,85,Kabupaten Madiun,2018,1
3,2018-01-04,25.7,37.4,88,Kabupaten Madiun,2018,1
4,2018-01-05,26.1,2.8,84,Kabupaten Madiun,2018,1

In [445]:
# Mengubah isi kolom Bulan dari angka menjadi Alfabet
bulan_mapping = {
    1: 'Januari',
    2: 'Februari',
    3: 'Maret',
    4: 'April',
    5: 'Mei',
    6: 'Juni',
    7: 'Juli',
    8: 'Agustus',
    9: 'September',
    10: 'Oktober',
    11: 'November',
    12: 'Desember'
}

df_cuaca_raw['Bulan'] = df_cuaca_raw['Bulan'].map(bulan_mapping)

df_cuaca_raw.head()

,time,temperature_2m_mean (°C),precipitation_sum (mm),relative_humidity_2m_mean (%),Wilayah,Tahun,Bulan
0,2018-01-01,26.6,5.6,79,Kabupaten Madiun,2018,Januari
1,2018-01-02,26.2,2.8,84,Kabupaten Madiun,2018,Januari
2,2018-01-03,26.1,3.1,85,Kabupaten Madiun,2018,Januari
3,2018-01-04,25.7,37.4,88,Kabupaten Madiun,2018,Januari
4,2018-01-05,26.1,2.8,84,Kabupaten Madiun,2018,Januari

In [446]:
# Mengubah Frekuensi waktu data cuaca dari harian menjadi bulanan
df_cuaca_bulanan = df_cuaca_raw.groupby(
    ['Wilayah', 'Tahun', 'Bulan']
).agg({
    'temperature_2m_mean (°C)': 'mean',
    'precipitation_sum (mm)': 'sum',
    'relative_humidity_2m_mean (%)': 'mean'
}).reset_index()

df_cuaca_bulanan.head()

,Wilayah,Tahun,Bulan,temperature_2m_mean (°C),precipitation_sum (mm),relative_humidity_2m_mean (%)
0,Kabupaten Bangkalan,2018,Agustus,26.909677,4.9,66.838710
1,Kabupaten Bangkalan,2018,April,26.593333,130.3,84.333333
2,Kabupaten Bangkalan,2018,Desember,26.419355,326.9,86.967742
3,Kabupaten Bangkalan,2018,Februari,25.546429,375.9,88.071429
4,Kabupaten Bangkalan,2018,Januari,25.703226,375.5,88.064516

In [447]:
# Mengubah nama kolom agar mudah dipahami
df_cuaca_bulanan.rename(columns={
    'temperature_2m_mean (°C)': 'Rata_Rata_Suhu',
    'precipitation_sum (mm)': 'Total_Curah_Hujan',
    'relative_humidity_2m_mean (%)': 'Rata_Rata_Kelembapan'
}, inplace=True)

df_cuaca_bulanan.head()

,Wilayah,Tahun,Bulan,Rata_Rata_Suhu,Total_Curah_Hujan,Rata_Rata_Kelembapan
0,Kabupaten Bangkalan,2018,Agustus,26.909677,4.9,66.838710
1,Kabupaten Bangkalan,2018,April,26.593333,130.3,84.333333
2,Kabupaten Bangkalan,2018,Desember,26.419355,326.9,86.967742
3,Kabupaten Bangkalan,2018,Februari,25.546429,375.9,88.071429
4,Kabupaten Bangkalan,2018,Januari,25.703226,375.5,88.064516

In [448]:
# Membuat kolom baru Urutan bulan agar bulan bisa urut Dari Januari Samapi Desember
urutan_bulan = {
    'Januari': 1,
    'Februari': 2,
    'Maret': 3,
    'April': 4,
    'Mei': 5,
    'Juni': 6,
    'Juli': 7,
    'Agustus': 8,
    'September': 9,
    'Oktober': 10,
    'November': 11,
    'Desember': 12
}

df_cuaca_bulanan['Urutan_Bulan'] = df_cuaca_bulanan['Bulan'].map(urutan_bulan)

# Data diurutkan berdasarkan Wilayah terlebih dahulu.Di dalam setiap wilayah, data diurutkan berdasarkan Tahun. Di dalam setiap tahun, data diurutkan berdasarkan Urutan_Bulan.
df_cuaca_bulanan = df_cuaca_bulanan.sort_values(
    by=['Wilayah', 'Tahun', 'Urutan_Bulan']
)
df_cuaca_bulanan.head()

,Wilayah,Tahun,Bulan,Rata_Rata_Suhu,Total_Curah_Hujan,Rata_Rata_Kelembapan,Urutan_Bulan
4,Kabupaten Bangkalan,2018,Januari,25.703226,375.5,88.064516,1
3,Kabupaten Bangkalan,2018,Februari,25.546429,375.9,88.071429,2
7,Kabupaten Bangkalan,2018,Maret,25.829032,440.6,87.903226,3
1,Kabupaten Bangkalan,2018,April,26.593333,130.3,84.333333,4
8,Kabupaten Bangkalan,2018,Mei,27.377419,52.8,75.709677,5

In [449]:
df_cuaca_bulanan.drop(columns='Urutan_Bulan', inplace=True)

df_cuaca_bulanan.head()

,Wilayah,Tahun,Bulan,Rata_Rata_Suhu,Total_Curah_Hujan,Rata_Rata_Kelembapan
4,Kabupaten Bangkalan,2018,Januari,25.703226,375.5,88.064516
3,Kabupaten Bangkalan,2018,Februari,25.546429,375.9,88.071429
7,Kabupaten Bangkalan,2018,Maret,25.829032,440.6,87.903226
1,Kabupaten Bangkalan,2018,April,26.593333,130.3,84.333333
8,Kabupaten Bangkalan,2018,Mei,27.377419,52.8,75.709677

# Pipeline Data Produksi Padi

In [450]:
# Baca data produksi padi
df_padi_raw = pd.read_csv('/content/padi/Produksi Padi Menurut KabupatenKota (Ton).csv')
df_padi_raw.head(10)

,Kabupaten/Kota Se Jawa Timur,Produksi Padi Menurut Kabupaten/Kota (Ton),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91
0,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,...,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
2,Kabupaten Pacitan,3113.91,9298.99,22928.59,12468.81,7102.87,9847.13,13351.29,5124.13,2533.14,...,24184.8,16062.1,3167.94,2024.01,7074.23,2274.74,1048.04,376.7,1988.93,69650.98
3,Kabupaten Ponorogo,202.2,4092.37,84787.64,85947.48,1728.29,19686.87,91559.34,31102.38,5985.77,...,97544.06,26975.57,14438.98,47397.46,55669.54,25458.43,3247.33,7482.04,41333.06,379244.91
4,Kabupaten Trenggalek,97.07,2943.02,28681.52,21859.55,5343.73,2913.26,21422.51,13585.82,8319.57,...,27952.25,17497.94,6105.63,7190.48,20765.44,4453.95,5345.06,2882.99,3819.13,104859.35
5,Kabupaten Tulungagung,2210.32,11479.46,35537.57,65542.98,10914.95,6344.94,16147.51,40925.79,14358.72,...,38892.89,42110.8,27817.51,7922.19,25597.26,16160.7,21073.99,11947.9,3070.97,214820.77
6,Kabupaten Blitar,2123.29,9013.42,38862.23,61519.8,32247.23,8911.26,19805.22,11956.61,11326.11,...,33912.17,51445.49,17095.68,4675.76,6904.23,11959.52,10580.12,12210.44,4448,171154.02
7,Kabupaten Kediri,3391.66,12358.98,68788.9,34595,9261.07,12542.02,35752.48,13536.18,6343.24,...,43962.98,10789.87,5172.9,23642.82,18307.1,7389.2,3892.17,5754.64,7743.73,174072.2
8,Kabupaten Malang,12267.24,11593.92,28946.68,55664.58,27351.58,27238.83,15560.16,22119.22,29991.31,...,23956.37,39240.68,40303.9,27318.54,13516.88,11616.02,20183.79,20588.58,15591.82,254793.72
9,Kabupaten Lumajang,12003.15,17676.5,40959.73,50655.28,27033.08,19094.26,32128.64,38502.16,12114.68,...,39259.49,35045.14,23910.3,18379.41,27981.16,22592.93,12990.92,16588.7,14460.25,257120.65

Transformasi format data dari Wide ke Long

In [451]:
# mengambil tahun dan bulan dari header data BPS agar nantinya bisa digabung menjadi nama kolom yang lengkap
tahun = df_padi_raw.iloc[0].ffill()
bulan = df_padi_raw.iloc[1]

In [452]:
# Membuat list untuk menyimpan nama kolom baru
new_columns = []

# Melakukan perulangan pada seluruh kolom dataset
for i in range(len(df_padi_raw.columns)):

    # Mengubah nama kolom pertama menjadi Wilayah
    if i == 0:
        new_columns.append('Wilayah')

    # Menggabungkan nama bulan dan tahun sebagai nama kolom
    else:
        col_name = f"{bulan[i]}_{int(tahun[i])}"
        new_columns.append(col_name)

/tmp/ipykernel_2249/2211806404.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  col_name = f"{bulan[i]}_{int(tahun[i])}"

In [453]:
# Mengambil data produksi padi dan menghapus baris header yang tidak diperlukan
df_padi = df_padi_raw.iloc[2:].copy()

# Mengganti nama kolom dengan nama kolom yang telah dibuat sebelumnya
df_padi.columns = new_columns

# Menampilkan 5 baris pertama dataset
df_padi.head()

,Wilayah,Januari_2018,Februari_2018,Maret_2018,April_2018,Mei_2018,Juni_2018,Juli_2018,Agustus_2018,September_2018,...,April_2024,Mei_2024,Juni_2024,Juli_2024,Agustus_2024,September_2024,Oktober_2024,November_2024,Desember_2024,Tahunan_2024
2,Kabupaten Pacitan,3113.91,9298.99,22928.59,12468.81,7102.87,9847.13,13351.29,5124.13,2533.14,...,24184.8,16062.1,3167.94,2024.01,7074.23,2274.74,1048.04,376.7,1988.93,69650.98
3,Kabupaten Ponorogo,202.2,4092.37,84787.64,85947.48,1728.29,19686.87,91559.34,31102.38,5985.77,...,97544.06,26975.57,14438.98,47397.46,55669.54,25458.43,3247.33,7482.04,41333.06,379244.91
4,Kabupaten Trenggalek,97.07,2943.02,28681.52,21859.55,5343.73,2913.26,21422.51,13585.82,8319.57,...,27952.25,17497.94,6105.63,7190.48,20765.44,4453.95,5345.06,2882.99,3819.13,104859.35
5,Kabupaten Tulungagung,2210.32,11479.46,35537.57,65542.98,10914.95,6344.94,16147.51,40925.79,14358.72,...,38892.89,42110.8,27817.51,7922.19,25597.26,16160.7,21073.99,11947.9,3070.97,214820.77
6,Kabupaten Blitar,2123.29,9013.42,38862.23,61519.8,32247.23,8911.26,19805.22,11956.61,11326.11,...,33912.17,51445.49,17095.68,4675.76,6904.23,11959.52,10580.12,12210.44,4448,171154.02

Menghapus kolom Serta baris yang tidak diperlukan

In [454]:
print("Jumlah kolom baru:", len(new_columns))

Jumlah kolom baru: 92

In [455]:
print(new_columns)

['Wilayah', 'Januari_2018', 'Februari_2018', 'Maret_2018', 'April_2018', 'Mei_2018', 'Juni_2018', 'Juli_2018', 'Agustus_2018', 'September_2018', 'Oktober_2018', 'November_2018', 'Desember_2018', 'Tahunan_2018', 'Januari_2019', 'Februari_2019', 'Maret_2019', 'April_2019', 'Mei_2019', 'Juni_2019', 'Juli_2019', 'Agustus_2019', 'September_2019', 'Oktober_2019', 'November_2019', 'Desember_2019', 'Tahunan_2019', 'Januari_2020', 'Februari_2020', 'Maret_2020', 'April_2020', 'Mei_2020', 'Juni_2020', 'Juli_2020', 'Agustus_2020', 'September_2020', 'Oktober_2020', 'November_2020', 'Desember_2020', 'Tahunan_2020', 'Januari_2021', 'Februari_2021', 'Maret_2021', 'April_2021', 'Mei_2021', 'Juni_2021', 'Juli_2021', 'Agustus_2021', 'September_2021', 'Oktober_2021', 'November_2021', 'Desember_2021', 'Tahunan_2021', 'Januari_2022', 'Februari_2022', 'Maret_2022', 'April_2022', 'Mei_2022', 'Juni_2022', 'Juli_2022', 'Agustus_2022', 'September_2022', 'Oktober_2022', 'November_2022', 'Desember_2022', 'Tahunan_2022', 'Januari_2023', 'Februari_2023', 'Maret_2023', 'April_2023', 'Mei_2023', 'Juni_2023', 'Juli_2023', 'Agustus_2023', 'September_2023', 'Oktober_2023', 'November_2023', 'Desember_2023', 'Tahunan_2023', 'Januari_2024', 'Februari_2024', 'Maret_2024', 'April_2024', 'Mei_2024', 'Juni_2024', 'Juli_2024', 'Agustus_2024', 'September_2024', 'Oktober_2024', 'November_2024', 'Desember_2024', 'Tahunan_2024']

In [456]:
kolom_tahunan = [
    col for col in df_padi.columns
    if 'Tahunan' in col
]

print(kolom_tahunan)

['Tahunan_2018', 'Tahunan_2019', 'Tahunan_2020', 'Tahunan_2021', 'Tahunan_2022', 'Tahunan_2023', 'Tahunan_2024']

In [457]:
df_padi.drop(
    columns=kolom_tahunan,
    inplace=True
)

In [458]:
print(len(df_padi.columns))

85

In [459]:
df_padi['Wilayah'].unique()

array(['Kabupaten Pacitan', 'Kabupaten Ponorogo', 'Kabupaten Trenggalek',
       'Kabupaten Tulungagung', 'Kabupaten Blitar', 'Kabupaten Kediri',
       'Kabupaten Malang', 'Kabupaten Lumajang', 'Kabupaten Jember',
       'Kabupaten Banyuwangi', 'Kabupaten Bondowoso',
       'Kabupaten Situbondo', 'Kabupaten Probolinggo',
       'Kabupaten Pasuruan', 'Kabupaten Sidoarjo', 'Kabupaten Mojokerto',
       'Kabupaten Jombang', 'Kabupaten Nganjuk', 'Kabupaten Madiun',
       'Kabupaten Magetan', 'Kabupaten Ngawi', 'Kabupaten Bojonegoro',
       'Kabupaten Tuban', 'Kabupaten Lamongan', 'Kabupaten Gresik',
       'Kabupaten Bangkalan', 'Kabupaten Sampang', 'Kabupaten Pamekasan',
       'Kabupaten Sumenep', 'Kota Kediri', 'Kota Blitar', 'Kota Malang',
       'Kota Probolinggo', 'Kota Pasuruan', 'Kota Mojokerto',
       'Kota Madiun', 'Kota Surabaya', 'Kota Batu', 'Jawa Timur', nan,
       'Catatan'], dtype=object)

In [460]:
# Menghapus baris Jawa Timur dan Wilayah sebelum dilakukan Melt
df_padi = df_padi[
    ~df_padi['Wilayah'].isin(
        ['Jawa Timur', 'Catatan']
    )
]

In [461]:
# Menghapus baris yang kosong didalam kolom wilayah
df_padi = df_padi.dropna(
    subset=['Wilayah']
)

In [462]:
df_padi['Wilayah'].unique()

array(['Kabupaten Pacitan', 'Kabupaten Ponorogo', 'Kabupaten Trenggalek',
       'Kabupaten Tulungagung', 'Kabupaten Blitar', 'Kabupaten Kediri',
       'Kabupaten Malang', 'Kabupaten Lumajang', 'Kabupaten Jember',
       'Kabupaten Banyuwangi', 'Kabupaten Bondowoso',
       'Kabupaten Situbondo', 'Kabupaten Probolinggo',
       'Kabupaten Pasuruan', 'Kabupaten Sidoarjo', 'Kabupaten Mojokerto',
       'Kabupaten Jombang', 'Kabupaten Nganjuk', 'Kabupaten Madiun',
       'Kabupaten Magetan', 'Kabupaten Ngawi', 'Kabupaten Bojonegoro',
       'Kabupaten Tuban', 'Kabupaten Lamongan', 'Kabupaten Gresik',
       'Kabupaten Bangkalan', 'Kabupaten Sampang', 'Kabupaten Pamekasan',
       'Kabupaten Sumenep', 'Kota Kediri', 'Kota Blitar', 'Kota Malang',
       'Kota Probolinggo', 'Kota Pasuruan', 'Kota Mojokerto',
       'Kota Madiun', 'Kota Surabaya', 'Kota Batu'], dtype=object)

In [463]:
# Mengubah data dari format lebar (wide) menjadi format panjang (long)
df_padi_long = pd.melt(
    df_padi,
    id_vars=['Wilayah'],
    var_name='Periode',
    value_name='Produksi_Padi'
)

# Menampilkan 5 baris pertama data
df_padi_long.head()

                 Wilayah       Periode Produksi_Padi
0      Kabupaten Pacitan  Januari_2018       3113.91
1     Kabupaten Ponorogo  Januari_2018         202.2
2   Kabupaten Trenggalek  Januari_2018         97.07
3  Kabupaten Tulungagung  Januari_2018       2210.32
4       Kabupaten Blitar  Januari_2018       2123.29

In [464]:
# Memisahkan informasi bulan dan tahun dari kolom Periode ke kolom baru
df_padi_long[['Bulan', 'Tahun']] = df_padi_long['Periode'].str.split('_', expand=True)

In [465]:
# Mengatur urutan kolom sesuai kebutuhan analisis
df_padi_long = df_padi_long[
    ['Wilayah', 'Tahun', 'Bulan', 'Produksi_Padi']
]

# Menampilkan 5 baris pertama data
df_padi_long.head()

                 Wilayah Tahun    Bulan Produksi_Padi
0      Kabupaten Pacitan  2018  Januari       3113.91
1     Kabupaten Ponorogo  2018  Januari         202.2
2   Kabupaten Trenggalek  2018  Januari         97.07
3  Kabupaten Tulungagung  2018  Januari       2210.32
4       Kabupaten Blitar  2018  Januari       2123.29

In [466]:
df_padi_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Wilayah        3192 non-null   object
 1   Tahun          3192 non-null   object
 2   Bulan          3192 non-null   object
 3   Produksi_Padi  3192 non-null   object
dtypes: object(4)
memory usage: 99.9+ KB

In [467]:
# Konversi tipe data tahun dan produksi padi menjadi numeric
df_padi_long['Tahun'] = pd.to_numeric(
    df_padi_long['Tahun']
)

df_padi_long['Produksi_Padi'] = pd.to_numeric(
    df_padi_long['Produksi_Padi'],
    errors='coerce'
)

In [468]:
df_padi_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Wilayah        3192 non-null   object
 1   Tahun          3192 non-null   int64
 2   Bulan          3192 non-null   object
 3   Produksi_Padi  3155 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 99.9+ KB

# Pipeline data luas panen

In [469]:
df_luas_raw = pd.read_csv('/content/padi/Query Builder Result - Minggu, 07 Juni 2026 pukul 11.27.08 WIB.csv')
df_luas_raw.head()

,Kabupaten/Kota Se Jawa Timur,Luas Panen Padi Menurut Kabupaten/Kota (Hektar),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91
0,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,...,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
2,Kabupaten Pacitan,807,2219,4762,2415,1518,2221,2825,1114,556,...,5009.7,3330.43,649.14,414.22,1450.87,442.16,203.6,71.53,384.64,14602.85
3,Kabupaten Ponorogo,33,668,13843,14047,315,3579,16651,5657,891,...,16753.16,4675.3,2501.67,8212.47,9646.08,3729.04,475.47,1096.45,6052.44,63395.6
4,Kabupaten Trenggalek,17,504,5118,3759,1083,580,4298,2714,1649,...,4599.55,3090.94,1067,1272.62,3643.84,839.97,1005.75,542.15,722.34,18239.46

In [470]:
# mengambil tahun dan bulan dari header data BPS agar nantinya bisa digabung menjadi nama kolom yang lengkap
tahun = df_luas_raw.iloc[0].ffill()
bulan = df_luas_raw.iloc[1]

In [471]:
# Membuat list untuk menyimpan nama kolom baru
new_columns = []

# Melakukan perulangan pada seluruh kolom dataset
for i in range(len(df_luas_raw.columns)):

    # Mengubah nama kolom pertama menjadi Wilayah
    if i == 0:
        new_columns.append('Wilayah')

    # Menggabungkan nama bulan dan tahun sebagai nama kolom
    else:
        col_name = f"{bulan[i]}_{int(tahun[i])}"
        new_columns.append(col_name)

/tmp/ipykernel_2249/84480333.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  col_name = f"{bulan[i]}_{int(tahun[i])}"

In [472]:
# Mengambil data luas padi dan menghapus baris header yang tidak diperlukan
df_luas = df_luas_raw.iloc[2:].copy()

# Mengganti nama kolom dengan nama kolom yang telah dibuat sebelumnya
df_luas.columns = new_columns

# Menampilkan 5 baris pertama dataset
df_luas.head()

,Wilayah,Januari_2018,Februari_2018,Maret_2018,April_2018,Mei_2018,Juni_2018,Juli_2018,Agustus_2018,September_2018,...,April_2024,Mei_2024,Juni_2024,Juli_2024,Agustus_2024,September_2024,Oktober_2024,November_2024,Desember_2024,Tahunan_2024
2,Kabupaten Pacitan,807,2219,4762,2415,1518,2221,2825,1114,556,...,5009.7,3330.43,649.14,414.22,1450.87,442.16,203.6,71.53,384.64,14602.85
3,Kabupaten Ponorogo,33,668,13843,14047,315,3579,16651,5657,891,...,16753.16,4675.3,2501.67,8212.47,9646.08,3729.04,475.47,1096.45,6052.44,63395.6
4,Kabupaten Trenggalek,17,504,5118,3759,1083,580,4298,2714,1649,...,4599.55,3090.94,1067,1272.62,3643.84,839.97,1005.75,542.15,722.34,18239.46
5,Kabupaten Tulungagung,318,1649,5143,9415,1964,1142,2906,7365,2594,...,6294.13,6795.19,4488.76,1278.36,4130.49,2451.33,3196.6,1812.32,465.82,34167.99
6,Kabupaten Blitar,344,1544,6417,10042,5677,1584,3495,2099,1675,...,5976.4,10138.61,3261.73,908.17,1360.62,1825.01,1614.52,1863.3,678.76,30789.76

In [473]:
print("Jumlah kolom baru:", len(new_columns))
print(new_columns)

Jumlah kolom baru: 92
['Wilayah', 'Januari_2018', 'Februari_2018', 'Maret_2018', 'April_2018', 'Mei_2018', 'Juni_2018', 'Juli_2018', 'Agustus_2018', 'September_2018', 'Oktober_2018', 'November_2018', 'Desember_2018', 'Tahunan_2018', 'Januari_2019', 'Februari_2019', 'Maret_2019', 'April_2019', 'Mei_2019', 'Juni_2019', 'Juli_2019', 'Agustus_2019', 'September_2019', 'Oktober_2019', 'November_2019', 'Desember_2019', 'Tahunan_2019', 'Januari_2020', 'Februari_2020', 'Maret_2020', 'April_2020', 'Mei_2020', 'Juni_2020', 'Juli_2020', 'Agustus_2020', 'September_2020', 'Oktober_2020', 'November_2020', 'Desember_2020', 'Tahunan_2020', 'Januari_2021', 'Februari_2021', 'Maret_2021', 'April_2021', 'Mei_2021', 'Juni_2021', 'Juli_2021', 'Agustus_2021', 'September_2021', 'Oktober_2021', 'November_2021', 'Desember_2021', 'Tahunan_2021', 'Januari_2022', 'Februari_2022', 'Maret_2022', 'April_2022', 'Mei_2022', 'Juni_2022', 'Juli_2022', 'Agustus_2022', 'September_2022', 'Oktober_2022', 'November_2022', 'Desember_2022', 'Tahunan_2022', 'Januari_2023', 'Februari_2023', 'Maret_2023', 'April_2023', 'Mei_2023', 'Juni_2023', 'Juli_2023', 'Agustus_2023', 'September_2023', 'Oktober_2023', 'November_2023', 'Desember_2023', 'Tahunan_2023', 'Januari_2024', 'Februari_2024', 'Maret_2024', 'April_2024', 'Mei_2024', 'Juni_2024', 'Juli_2024', 'Agustus_2024', 'September_2024', 'Oktober_2024', 'November_2024', 'Desember_2024', 'Tahunan_2024']

In [474]:
kolom_tahunan = [
    col for col in df_luas.columns
    if 'Tahunan' in col
]

print(kolom_tahunan)

['Tahunan_2018', 'Tahunan_2019', 'Tahunan_2020', 'Tahunan_2021', 'Tahunan_2022', 'Tahunan_2023', 'Tahunan_2024']

In [475]:
df_luas.drop(
    columns=kolom_tahunan,
    inplace=True
)

In [476]:
print(len(df_luas.columns))

85

In [477]:
df_luas['Wilayah'].unique()

array(['Kabupaten Pacitan', 'Kabupaten Ponorogo', 'Kabupaten Trenggalek',
       'Kabupaten Tulungagung', 'Kabupaten Blitar', 'Kabupaten Kediri',
       'Kabupaten Malang', 'Kabupaten Lumajang', 'Kabupaten Jember',
       'Kabupaten Banyuwangi', 'Kabupaten Bondowoso',
       'Kabupaten Situbondo', 'Kabupaten Probolinggo',
       'Kabupaten Pasuruan', 'Kabupaten Sidoarjo', 'Kabupaten Mojokerto',
       'Kabupaten Jombang', 'Kabupaten Nganjuk', 'Kabupaten Madiun',
       'Kabupaten Magetan', 'Kabupaten Ngawi', 'Kabupaten Bojonegoro',
       'Kabupaten Tuban', 'Kabupaten Lamongan', 'Kabupaten Gresik',
       'Kabupaten Bangkalan', 'Kabupaten Sampang', 'Kabupaten Pamekasan',
       'Kabupaten Sumenep', 'Kota Kediri', 'Kota Blitar', 'Kota Malang',
       'Kota Probolinggo', 'Kota Pasuruan', 'Kota Mojokerto',
       'Kota Madiun', 'Kota Surabaya', 'Kota Batu', 'Jawa Timur', nan,
       'Catatan'], dtype=object)

In [478]:
df_luas = df_luas[
    ~df_luas['Wilayah'].isin(
        ['Jawa Timur', 'Catatan']
    )
]

df_luas = df_luas.dropna(
    subset=['Wilayah']
)

In [479]:
print(df_luas['Wilayah'].nunique())

38

In [480]:
# Mengubah data dari format lebar (wide) menjadi format panjang (long)
df_luas_long = pd.melt(
    df_luas,
    id_vars=['Wilayah'],
    var_name='Periode',
    value_name='Luas_Panen'
)

# Menampilkan 5 baris pertama data
df_luas_long.head()

                 Wilayah       Periode Luas_Panen
0      Kabupaten Pacitan  Januari_2018        807
1     Kabupaten Ponorogo  Januari_2018         33
2   Kabupaten Trenggalek  Januari_2018         17
3  Kabupaten Tulungagung  Januari_2018        318
4       Kabupaten Blitar  Januari_2018        344

In [481]:
# Memisahkan informasi bulan dan tahun dari kolom Periode ke kolom baru
df_luas_long[['Bulan', 'Tahun']] = df_luas_long['Periode'].str.split('_', expand=True)

In [482]:
# Mengatur urutan kolom sesuai kebutuhan analisis
df_luas_long = df_luas_long[
    ['Wilayah', 'Tahun', 'Bulan', 'Luas_Panen']
]

# Menampilkan 5 baris pertama data
df_luas_long.head()

                 Wilayah Tahun    Bulan Luas_Panen
0      Kabupaten Pacitan  2018  Januari        807
1     Kabupaten Ponorogo  2018  Januari         33
2   Kabupaten Trenggalek  2018  Januari         17
3  Kabupaten Tulungagung  2018  Januari        318
4       Kabupaten Blitar  2018  Januari        344

In [483]:
df_luas_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Wilayah     3192 non-null   object
 1   Tahun       3192 non-null   object
 2   Bulan       3192 non-null   object
 3   Luas_Panen  3192 non-null   object
dtypes: object(4)
memory usage: 99.9+ KB

In [484]:
df_luas_long['Tahun'] = pd.to_numeric(
    df_luas_long['Tahun']
)

df_luas_long['Luas_Panen'] = pd.to_numeric(
    df_luas_long['Luas_Panen'],
    errors='coerce'
)

In [485]:
df_luas_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Wilayah     3192 non-null   object
 1   Tahun       3192 non-null   int64
 2   Bulan       3192 non-null   object
 3   Luas_Panen  3152 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 99.9+ KB

In [486]:
df_luas_long.head()

                 Wilayah  Tahun    Bulan  Luas_Panen
0      Kabupaten Pacitan   2018  Januari       807.0
1     Kabupaten Ponorogo   2018  Januari        33.0
2   Kabupaten Trenggalek   2018  Januari        17.0
3  Kabupaten Tulungagung   2018  Januari       318.0
4       Kabupaten Blitar   2018  Januari       344.0

# Analisis ulang untuk memastikan kesesuaian type data dataset sebelum dilkaukan Merge

In [487]:
df_padi_long.info()
df_cuaca_bulanan.info()
df_luas_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Wilayah        3192 non-null   object
 1   Tahun          3192 non-null   int64
 2   Bulan          3192 non-null   object
 3   Produksi_Padi  3155 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 99.9+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 3192 entries, 4 to 3182
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Wilayah               3192 non-null   object
 1   Tahun                 3192 non-null   int32
 2   Bulan                 3192 non-null   object
 3   Rata_Rata_Suhu        3192 non-null   float64
 4   Total_Curah_Hujan     3192 non-null   float64
 5   Rata_Rata_Kelembapan  3192 non-null   float64
dtypes: float64(3), int32(1), object(2)
memory usage: 162.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Wilayah     3192 non-null   object
 1   Tahun       3192 non-null   int64
 2   Bulan       3192 non-null   object
 3   Luas_Panen  3152 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 99.9+ KB

In [488]:
print(df_cuaca_bulanan.head())
print(df_padi_long.head())
print(df_luas_long.head())

               Wilayah  Tahun     Bulan  Rata_Rata_Suhu  Total_Curah_Hujan  \
4  Kabupaten Bangkalan   2018   Januari       25.703226              375.5
3  Kabupaten Bangkalan   2018  Februari       25.546429              375.9
7  Kabupaten Bangkalan   2018     Maret       25.829032              440.6
1  Kabupaten Bangkalan   2018     April       26.593333              130.3
8  Kabupaten Bangkalan   2018       Mei       27.377419               52.8

   Rata_Rata_Kelembapan
4             88.064516
3             88.071429
7             87.903226
1             84.333333
8             75.709677
                 Wilayah  Tahun    Bulan  Produksi_Padi
0      Kabupaten Pacitan   2018  Januari        3113.91
1     Kabupaten Ponorogo   2018  Januari         202.20
2   Kabupaten Trenggalek   2018  Januari          97.07
3  Kabupaten Tulungagung   2018  Januari        2210.32
4       Kabupaten Blitar   2018  Januari        2123.29
                 Wilayah  Tahun    Bulan  Luas_Panen
0      Kabupaten Pacitan   2018  Januari       807.0
1     Kabupaten Ponorogo   2018  Januari        33.0
2   Kabupaten Trenggalek   2018  Januari        17.0
3  Kabupaten Tulungagung   2018  Januari       318.0
4       Kabupaten Blitar   2018  Januari       344.0

In [489]:
# Menyamakan tipe data kolom Tahun pada seluruh dataset
df_padi_long['Tahun'] = df_padi_long['Tahun'].astype(int)
df_cuaca_bulanan['Tahun'] = df_cuaca_bulanan['Tahun'].astype(int)
df_luas_long['Tahun'] = df_luas_long['Tahun'].astype(int)

# Merge Data produksi padi, dan luas panen

In [490]:
df_padi_luas = pd.merge(
    df_padi_long,
    df_luas_long,
    on=['Wilayah', 'Tahun', 'Bulan'],
    how='inner'
)

print(df_padi_luas.shape)
df_padi_luas.head()

(3192, 5)

                 Wilayah  Tahun    Bulan  Produksi_Padi  Luas_Panen
0      Kabupaten Pacitan   2018  Januari        3113.91       807.0
1     Kabupaten Ponorogo   2018  Januari         202.20        33.0
2   Kabupaten Trenggalek   2018  Januari          97.07        17.0
3  Kabupaten Tulungagung   2018  Januari        2210.32       318.0
4       Kabupaten Blitar   2018  Januari        2123.29       344.0

In [491]:
# Menghitung Produktivitas berdasarkan produksi serta luas panen
df_padi_luas['Produktivitas_Ton_Ha'] = (
    df_padi_luas['Produksi_Padi']
    / df_padi_luas['Luas_Panen']
)

In [492]:
df_padi_luas.head()

,Wilayah,Tahun,Bulan,Produksi_Padi,Luas_Panen,Produktivitas_Ton_Ha
0,Kabupaten Pacitan,2018,Januari,3113.91,807.0,3.858625
1,Kabupaten Ponorogo,2018,Januari,202.20,33.0,6.127273
2,Kabupaten Trenggalek,2018,Januari,97.07,17.0,5.710000
3,Kabupaten Tulungagung,2018,Januari,2210.32,318.0,6.950692
4,Kabupaten Blitar,2018,Januari,2123.29,344.0,6.172355

Merge Dengan data Cuaca

In [493]:
df_final = pd.merge(
    df_padi_luas,
    df_cuaca_bulanan,
    on=['Wilayah', 'Tahun', 'Bulan'],
    how='inner'
)

df_final.head()

,Wilayah,Tahun,Bulan,Produksi_Padi,Luas_Panen,Produktivitas_Ton_Ha,Rata_Rata_Suhu,Total_Curah_Hujan,Rata_Rata_Kelembapan
0,Kabupaten Pacitan,2018,Januari,3113.91,807.0,3.858625,26.141935,371.3,86.161290
1,Kabupaten Ponorogo,2018,Januari,202.20,33.0,6.127273,26.293548,260.3,81.032258
2,Kabupaten Trenggalek,2018,Januari,97.07,17.0,5.710000,25.803226,238.3,84.741935
3,Kabupaten Tulungagung,2018,Januari,2210.32,318.0,6.950692,24.935484,302.4,88.161290
4,Kabupaten Blitar,2018,Januari,2123.29,344.0,6.172355,24.906452,372.9,85.774194

Analisa Final

In [494]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3192 entries, 0 to 3191
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Wilayah               3192 non-null   object
 1   Tahun                 3192 non-null   int64
 2   Bulan                 3192 non-null   object
 3   Produksi_Padi         3155 non-null   float64
 4   Luas_Panen            3152 non-null   float64
 5   Produktivitas_Ton_Ha  3022 non-null   float64
 6   Rata_Rata_Suhu        3192 non-null   float64
 7   Total_Curah_Hujan     3192 non-null   float64
 8   Rata_Rata_Kelembapan  3192 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 224.6+ KB

In [495]:
df_final['Produksi_Padi'].describe()

count      3155.000000
mean      21559.792285
std       30962.528687
min           0.000000
25%        1308.010000
50%       11117.080000
75%       27957.775000
max      283043.450000
Name: Produksi_Padi, dtype: float64

In [496]:
df_final['Luas_Panen'].describe()

count     3152.000000
mean      3795.606609
std       5384.005648
min          0.000000
25%        226.750000
50%       1950.500000
75%       5051.960000
max      49074.540000
Name: Luas_Panen, dtype: float64

In [497]:
df_final['Produktivitas_Ton_Ha'].describe()

count    3022.000000
mean             inf
std              NaN
min         0.991500
25%         5.246970
50%         5.771569
75%         6.243057
max              inf
Name: Produktivitas_Ton_Ha, dtype: float64

In [498]:
(df_final['Produksi_Padi'] == 0).sum()

np.int64(133)

In [499]:
(df_final['Luas_Panen'] == 0).sum()

np.int64(131)

In [500]:
import numpy as np

np.isinf(
    df_final['Produktivitas_Ton_Ha']
).sum()

np.int64(1)

In [501]:
df_final.isna().sum()

Wilayah                   0
Tahun                     0
Bulan                     0
Produksi_Padi            37
Luas_Panen               40
Produktivitas_Ton_Ha    170
Rata_Rata_Suhu            0
Total_Curah_Hujan         0
Rata_Rata_Kelembapan      0
dtype: int64

In [502]:
df_final[
    df_final['Produksi_Padi'].isna()
][['Wilayah','Tahun','Bulan']]

                  Wilayah  Tahun      Bulan
938     Kabupaten Sampang   2020    Januari
941           Kota Kediri   2020    Januari
942           Kota Blitar   2020    Januari
944      Kota Probolinggo   2020    Januari
980           Kota Blitar   2020   Februari
985           Kota Madiun   2020   Februari
1018          Kota Blitar   2020      Maret
1022       Kota Mojokerto   2020      Maret
1099          Kota Madiun   2020        Mei
1137          Kota Madiun   2020       Juni
1210     Kota Probolinggo   2020    Agustus
1248     Kota Probolinggo   2020  September
1251          Kota Madiun   2020  September
1284          Kota Blitar   2020    Oktober
1322          Kota Blitar   2020   November
1356    Kabupaten Sampang   2020   Desember
1359          Kota Kediri   2020   Desember
1360          Kota Blitar   2020   Desember
1362     Kota Probolinggo   2020   Desember
1364       Kota Mojokerto   2020   Desember
1400     Kota Probolinggo   2021    Januari
1402       Kota Mojokerto   2021    Januari
1440       Kota Mojokerto   2021   Februari
1441          Kota Madiun   2021   Februari
1630       Kota Mojokerto   2021       Juli
1668       Kota Mojokerto   2021    Agustus
1740          Kota Blitar   2021    Oktober
1742     Kota Probolinggo   2021    Oktober
1775  Kabupaten Pamekasan   2021   November
1777          Kota Kediri   2021   November
1778          Kota Blitar   2021   November
1811  Kabupaten Bangkalan   2021   Desember
1812    Kabupaten Sampang   2021   Desember
1813  Kabupaten Pamekasan   2021   Desember
1814    Kabupaten Sumenep   2021   Desember
1816          Kota Blitar   2021   Desember
1820       Kota Mojokerto   2021   Desember

In [503]:
df_final[
    df_final['Luas_Panen'].isna()
][['Wilayah','Tahun','Bulan']]

                  Wilayah  Tahun      Bulan
938     Kabupaten Sampang   2020    Januari
941           Kota Kediri   2020    Januari
942           Kota Blitar   2020    Januari
944      Kota Probolinggo   2020    Januari
980           Kota Blitar   2020   Februari
985           Kota Madiun   2020   Februari
1018          Kota Blitar   2020      Maret
1022       Kota Mojokerto   2020      Maret
1099          Kota Madiun   2020        Mei
1137          Kota Madiun   2020       Juni
1169          Kota Kediri   2020       Juli
1210     Kota Probolinggo   2020    Agustus
1248     Kota Probolinggo   2020  September
1251          Kota Madiun   2020  September
1284          Kota Blitar   2020    Oktober
1291            Kota Batu   2020    Oktober
1322          Kota Blitar   2020   November
1356    Kabupaten Sampang   2020   Desember
1359          Kota Kediri   2020   Desember
1360          Kota Blitar   2020   Desember
1362     Kota Probolinggo   2020   Desember
1364       Kota Mojokerto   2020   Desember
1400     Kota Probolinggo   2021    Januari
1402       Kota Mojokerto   2021    Januari
1440       Kota Mojokerto   2021   Februari
1441          Kota Madiun   2021   Februari
1555          Kota Madiun   2021        Mei
1630       Kota Mojokerto   2021       Juli
1668       Kota Mojokerto   2021    Agustus
1740          Kota Blitar   2021    Oktober
1742     Kota Probolinggo   2021    Oktober
1775  Kabupaten Pamekasan   2021   November
1777          Kota Kediri   2021   November
1778          Kota Blitar   2021   November
1811  Kabupaten Bangkalan   2021   Desember
1812    Kabupaten Sampang   2021   Desember
1813  Kabupaten Pamekasan   2021   Desember
1814    Kabupaten Sumenep   2021   Desember
1816          Kota Blitar   2021   Desember
1820       Kota Mojokerto   2021   Desember

In [504]:
df_final[
  df_final['Produksi_Padi'].isna()
]['Tahun'].value_counts().sort_index()

Tahun
2020    20
2021    17
Name: count, dtype: int64

In [505]:
df_final[
  df_final['Luas_Panen'].isna()
]['Tahun'].value_counts().sort_index()

Tahun
2020    22
2021    18
Name: count, dtype: int64

In [506]:
df_final[
    df_final['Produksi_Padi'].isna()
]['Wilayah'].value_counts()

Wilayah
Kota Blitar            9
Kota Mojokerto         7
Kota Probolinggo       6
Kota Madiun            5
Kabupaten Sampang      3
Kota Kediri            3
Kabupaten Pamekasan    2
Kabupaten Bangkalan    1
Kabupaten Sumenep      1
Name: count, dtype: int64

In [507]:
df_final[
    df_final['Luas_Panen'].isna()
]['Wilayah'].value_counts()

Wilayah
Kota Blitar            9
Kota Mojokerto         7
Kota Probolinggo       6
Kota Madiun            6
Kota Kediri            4
Kabupaten Sampang      3
Kabupaten Pamekasan    2
Kota Batu              1
Kabupaten Bangkalan    1
Kabupaten Sumenep      1
Name: count, dtype: int64

In [508]:
mask = (
    df_final['Produksi_Padi'].isna() &
    df_final['Luas_Panen'].isna()
)

mask.sum()

np.int64(37)

In [509]:
df_final[
    df_final['Luas_Panen'].isna() &
    df_final['Produksi_Padi'].notna()
][
    ['Wilayah','Tahun','Bulan',
     'Produksi_Padi','Luas_Panen']
]

          Wilayah  Tahun    Bulan  Produksi_Padi  Luas_Panen
1169  Kota Kediri   2020     Juli            0.0         NaN
1291    Kota Batu   2020  Oktober            0.0         NaN
1555  Kota Madiun   2021      Mei            0.0         NaN

In [510]:
import numpy as np

df_final = df_final.replace(
    [np.inf, -np.inf],
    np.nan
)

In [511]:
df_final = df_final.dropna(
    subset=['Produktivitas_Ton_Ha']
)

Hasil Analisis final adalah ada Data pada produksi padi Serta data luas panen yang bernali NaN dan 0, Sehingga hasil perhitungan produktivitas_padi_ton_ha Dari Produksi padi dan luas panen hasilnya NaN. Lalu kami  melakukan penghapusan baris produktivitas padi yang bernilai NaN dikarenakan data produksi padi serta data luas panen harus ada data aslinya, dan jumlah baris setelah masih 3000 an masih cukup untuk training model

## Validasi

In [512]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3021 entries, 0 to 3191
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Wilayah               3021 non-null   object
 1   Tahun                 3021 non-null   int64
 2   Bulan                 3021 non-null   object
 3   Produksi_Padi         3021 non-null   float64
 4   Luas_Panen            3021 non-null   float64
 5   Produktivitas_Ton_Ha  3021 non-null   float64
 6   Rata_Rata_Suhu        3021 non-null   float64
 7   Total_Curah_Hujan     3021 non-null   float64
 8   Rata_Rata_Kelembapan  3021 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 236.0+ KB

In [513]:
print(df_final.shape)

(3021, 9)

In [514]:
df_clean = df_final.copy()

# Rolling 4 Bulan data cuaca

In [515]:
urutan_bulan = {
    'Januari':1,
    'Februari':2,
    'Maret':3,
    'April':4,
    'Mei':5,
    'Juni':6,
    'Juli':7,
    'Agustus':8,
    'September':9,
    'Oktober':10,
    'November':11,
    'Desember':12
}

df_final['Bulan_Angka'] = df_final['Bulan'].map(urutan_bulan)
df_final.head()

,Wilayah,Tahun,Bulan,Produksi_Padi,Luas_Panen,Produktivitas_Ton_Ha,Rata_Rata_Suhu,Total_Curah_Hujan,Rata_Rata_Kelembapan,Bulan_Angka
0,Kabupaten Pacitan,2018,Januari,3113.91,807.0,3.858625,26.141935,371.3,86.161290,1
1,Kabupaten Ponorogo,2018,Januari,202.20,33.0,6.127273,26.293548,260.3,81.032258,1
2,Kabupaten Trenggalek,2018,Januari,97.07,17.0,5.710000,25.803226,238.3,84.741935,1
3,Kabupaten Tulungagung,2018,Januari,2210.32,318.0,6.950692,24.935484,302.4,88.161290,1
4,Kabupaten Blitar,2018,Januari,2123.29,344.0,6.172355,24.906452,372.9,85.774194,1

In [516]:
df_final = df_final.sort_values(
    ['Wilayah', 'Tahun', 'Bulan_Angka']
)

In [517]:
df_final[
    df_final['Wilayah'] == 'Kabupaten Pacitan'
][['Tahun','Bulan','Bulan_Angka']].head(15)

     Tahun      Bulan  Bulan_Angka
0     2018    Januari            1
38    2018   Februari            2
76    2018      Maret            3
114   2018      April            4
152   2018        Mei            5
190   2018       Juni            6
228   2018       Juli            7
266   2018    Agustus            8
304   2018  September            9
342   2018    Oktober           10
380   2018   November           11
418   2018   Desember           12
456   2019    Januari            1
494   2019   Februari            2
532   2019      Maret            3

Rolling 4 bulan

In [518]:
df_final['Suhu_4Bln'] = (
    df_final
    .groupby('Wilayah')['Rata_Rata_Suhu']
    .transform(
        lambda x: x.rolling(
            window=4,
            min_periods=4
        ).mean()
    )
)

In [519]:
df_final['Curah_4Bln'] = (
    df_final
    .groupby('Wilayah')['Total_Curah_Hujan']
    .transform(
        lambda x: x.rolling(
            window=4,
            min_periods=4
        ).sum()
    )
)

In [520]:
df_final['Kelembapan_4Bln'] = (
    df_final
    .groupby('Wilayah')['Rata_Rata_Kelembapan']
    .transform(
        lambda x: x.rolling(
            window=4,
            min_periods=4
        ).mean()
    )
)

In [521]:
df_final[
    df_final['Wilayah'] == 'Kabupaten Pacitan'
][[
    'Tahun',
    'Bulan',
    'Rata_Rata_Suhu',
    'Suhu_4Bln',
    'Total_Curah_Hujan',
    'Curah_4Bln',
    'Rata_Rata_Kelembapan',
    'Kelembapan_4Bln'
]].head(10)

,Tahun,Bulan,Rata_Rata_Suhu,Suhu_4Bln,Total_Curah_Hujan,Curah_4Bln,Rata_Rata_Kelembapan,Kelembapan_4Bln
0,2018,Januari,26.141935,NaN,371.3,NaN,86.161290,NaN
38,2018,Februari,26.114286,NaN,206.8,NaN,86.285714,NaN
76,2018,Maret,26.461290,NaN,194.6,NaN,86.677419,NaN
114,2018,April,26.930000,26.411878,114.8,887.5,85.200000,86.081106
152,2018,Mei,26.890323,26.598975,9.7,525.9,78.806452,84.242396
190,2018,Juni,26.100000,26.595403,24.3,343.4,79.833333,82.629301
228,2018,Juli,24.754839,26.168790,5.8,154.6,78.709677,80.637366
266,2018,Agustus,24.532258,25.569355,27.6,67.4,79.870968,79.305108
304,2018,September,25.240000,25.156774,46.6,104.3,81.700000,80.028495
342,2018,Oktober,26.300000,25.206774,46.4,126.4,80.870968,80.287903

In [522]:
df_final[
    [
        'Suhu_4Bln',
        'Curah_4Bln',
        'Kelembapan_4Bln'
    ]
].isna().sum()

Suhu_4Bln          114
Curah_4Bln         114
Kelembapan_4Bln    114
dtype: int64

In [523]:
# Menghapus baris bulan yang bernilai NaN dikarenakan tidak ada data historis cuaca pada bulan sebelumnya
df_final = df_final.dropna(
    subset=[
        'Suhu_4Bln',
        'Curah_4Bln',
        'Kelembapan_4Bln'
    ]
)

In [524]:
df_final.shape

(2907, 13)

In [525]:
df_final .head()

,Wilayah,Tahun,Bulan,Produksi_Padi,Luas_Panen,Produktivitas_Ton_Ha,Rata_Rata_Suhu,Total_Curah_Hujan,Rata_Rata_Kelembapan,Bulan_Angka,Suhu_4Bln,Curah_4Bln,Kelembapan_4Bln
139,Kabupaten Bangkalan,2018,April,27021.81,4477.0,6.035696,26.593333,130.3,84.333333,4,25.918005,1322.3,87.093126
177,Kabupaten Bangkalan,2018,Mei,12847.50,2218.0,5.792381,27.377419,52.8,75.709677,5,26.336553,999.6,84.004416
215,Kabupaten Bangkalan,2018,Juni,27605.63,4760.0,5.799502,27.130000,25.1,74.533333,6,26.732446,648.8,80.619892
253,Kabupaten Bangkalan,2018,Juli,37426.82,6435.0,5.816134,26.835484,4.7,68.935484,7,26.984059,212.9,75.877957
291,Kabupaten Bangkalan,2018,Agustus,10502.98,1811.0,5.799547,26.909677,4.9,66.838710,8,27.063145,87.5,71.504301

In [526]:
# Memilih kolom yang akan digunakan
df_final = df_final[
    [
        'Wilayah',
        'Tahun',
        'Bulan',
        'Produksi_Padi',
        'Luas_Panen',
        'Produktivitas_Ton_Ha',
        'Suhu_4Bln',
        'Curah_4Bln',
        'Kelembapan_4Bln'
    ]
]

In [527]:
df_final.head()

,Wilayah,Tahun,Bulan,Produksi_Padi,Luas_Panen,Produktivitas_Ton_Ha,Suhu_4Bln,Curah_4Bln,Kelembapan_4Bln
139,Kabupaten Bangkalan,2018,April,27021.81,4477.0,6.035696,25.918005,1322.3,87.093126
177,Kabupaten Bangkalan,2018,Mei,12847.50,2218.0,5.792381,26.336553,999.6,84.004416
215,Kabupaten Bangkalan,2018,Juni,27605.63,4760.0,5.799502,26.732446,648.8,80.619892
253,Kabupaten Bangkalan,2018,Juli,37426.82,6435.0,5.816134,26.984059,212.9,75.877957
291,Kabupaten Bangkalan,2018,Agustus,10502.98,1811.0,5.799547,27.063145,87.5,71.504301

# Menyimpan Ke Database AIVEN

In [528]:
#Install library
!pip install sqlalchemy pymysql cryptography

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.50)
Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.2.0)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (48.0.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography) (3.0)

In [ ]:
# Database connection parameters
db_user = 'your_username'
db_password = 'your_password'
db_host = 'localhost'
db_name = 'your_database'

In [530]:
df_final.head()

,Wilayah,Tahun,Bulan,Produksi_Padi,Luas_Panen,Produktivitas_Ton_Ha,Suhu_4Bln,Curah_4Bln,Kelembapan_4Bln
139,Kabupaten Bangkalan,2018,April,27021.81,4477.0,6.035696,25.918005,1322.3,87.093126
177,Kabupaten Bangkalan,2018,Mei,12847.50,2218.0,5.792381,26.336553,999.6,84.004416
215,Kabupaten Bangkalan,2018,Juni,27605.63,4760.0,5.799502,26.732446,648.8,80.619892
253,Kabupaten Bangkalan,2018,Juli,37426.82,6435.0,5.816134,26.984059,212.9,75.877957
291,Kabupaten Bangkalan,2018,Agustus,10502.98,1811.0,5.799547,27.063145,87.5,71.504301

In [532]:
# Membuat tabel di database aiven untuk menyimpan data final
from sqlalchemy import text

with engine.begin() as conn:

    conn.execute(text("""
    CREATE TABLE produktivitas_padi_cuaca (
        id INT AUTO_INCREMENT PRIMARY KEY,

        Wilayah VARCHAR(100),
        Tahun INT,
        Bulan VARCHAR(20),

        Produksi_Padi DOUBLE,
        Luas_Panen DOUBLE,
        Produktivitas_Ton_Ha DOUBLE,

        Suhu_4Bln DOUBLE,
        Curah_4Bln DOUBLE,
        Kelembapan_4Bln DOUBLE
    )
    """))

print("Tabel berhasil dibuat")

Tabel berhasil dibuat

In [533]:
# Cek tabel yang ada di aiven
from sqlalchemy import text
import pandas as pd

pd.read_sql(
    text("SHOW TABLES"),
    engine
)

        Tables_in_defaultdb
0         hasil_prediksi_rf
1       produksi_padi_cuaca
2  produktivitas_padi_cuaca
3                 test_padi

In [534]:
pd.read_sql(
    text("DESCRIBE produktivitas_padi_cuaca"),
    engine
)

                  Field          Type Null  Key Default           Extra
0                    id           int   NO  PRI    None  auto_increment
1               Wilayah  varchar(100)  YES         None
2                 Tahun           int  YES         None
3                 Bulan   varchar(20)  YES         None
4         Produksi_Padi        double  YES         None
5            Luas_Panen        double  YES         None
6  Produktivitas_Ton_Ha        double  YES         None
7             Suhu_4Bln        double  YES         None
8            Curah_4Bln        double  YES         None
9       Kelembapan_4Bln        double  YES         None

In [535]:
df_final.columns

Index(['Wilayah', 'Tahun', 'Bulan', 'Produksi_Padi', 'Luas_Panen',
       'Produktivitas_Ton_Ha', 'Suhu_4Bln', 'Curah_4Bln', 'Kelembapan_4Bln'],
      dtype='object')

In [536]:
df_final.to_sql(
    'produktivitas_padi_cuaca',
    con=engine,
    if_exists='append',
    index=False,
    method='multi'
)

2907

In [537]:
from sqlalchemy import text
import pandas as pd

pd.read_sql(
    text("SELECT COUNT(*) AS total FROM produktivitas_padi_cuaca"),
    engine
)

   total
0   2907